syntax on
filetype indent plugin on

set autoread
set nobackup
set noswapfile

set number
set relativenumber

set showcmd
set showmode

set incsearch
set smartcase
set ignorecase

set wildmenu
set wildmode=longest:full,full
set wildignorecase

set background=dark

set autoindent
set smartindent

set mouse=a

set grepformat=%f:%l:%c:%m

if executable('rg')
	set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
endif

augroup quickfix
	autocmd QuickFixCmdPost grep copen
augroup END

colorscheme everforest

cnoremap <C-B> <Left>
cnoremap <C-F> <Right>
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-L> <C-F>
