syntax on

filetype indent plugin on

set autoread
set nobackup
set noswapfile

set number
set relativenumber

set showcmd
set showmode

set incsearch
set smartcase
set ignorecase

set wildmenu
set wildmode=longest:full,full
set wildignorecase

set background=dark

inoremap <silent> <C-B> <Left>
inoremap <silent> <C-F> <Right>
inoremap <silent> <C-P> <Up>
inoremap <silent> <C-N> <Down>
inoremap <silent> <C-A> <Home>
inoremap <silent> <C-E> <End>

cnoremap <C-B> <Left>
cnoremap <C-F> <Right>
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-L> <C-F>
