require("plugins.mini.icons")
require("plugins.mini.tabline")
require("plugins.mini.statusline")
require("plugins.mini.bracketed")
require("plugins.mini.completion")
require("plugins.mini.pick")
require("plugins.mini.extra")
